Repository Icinga/icingaweb2-module-jira, pull requests merged in 2023-02, with the labels that each got.

#91 Remove Inspect tab from Jira->Configuration page
  application/controllers/ConfigurationController.php
Labels: cla/signed

#92 Feature/add object state change time
  library/Jira/MonitoringInfo.php
Labels: enhancement, cla/signed

#93 Fix issue with service names with '%' character
  application/controllers/IssuesController.php
  library/Jira/Web/Controller.php
Labels: bug, cla/signed

#94 Add additional method to fetch issues for specific project
  application/clicommands/SendCommand.php
  library/Jira/RestApi.php
Labels: bug, cla/signed

#79 make custom fields configurable
  application/clicommands/SendCommand.php
  doc/03-Configuration.md
  library/Jira/IssueTemplate.php
  library/Jira/RestApi.php
  library/Jira/Web/Table/IssueDetails.php
Labels: enhancement, cla/signed
